### ISSUE TITLE
TV effect stops working when some windows are closed

### ISSUE THREAD

**Issue by chrostino** [Schneegans/Burn-My-Windows#446]
## Describe the Bug
I tried only with tv effect, but other than some minor bugs (like it not displaying when opening firefox) the effect straight up stops working when interacting with some specific windows, like when closing steam or with some windows of windows programs being displayed through wine/proton (like ubisoft club, ea launcher or some games)

1. set "TV effect" as window open/close animation
2. start steam (for example)
3. close steam with the X icon in the top right before closing completely through the tray icon
4. the effect doesn't show
5. most of the time the effect doesn't stops working even on normal windows, the only way to make it work again is to set it again in settings

```
    at window_main_awaiter (/app/Bitwarden/resources/app.asar/main.js:89730:12)
    at WindowMain.updateWindowState (/app/Bitwarden/resources/app.asar/main.js:89967:16)
    at WindowMain.<anonymous> (/app/Bitwarden/resources/app.asar/main.js:89902:28)
    at Generator.next (<anonymous>)
    at /app/Bitwarden/resources/app.asar/main.js:89734:71
    at new Promise (<anonymous>)
app-flatpak-com.bitwarden.desktop-69434.scope: Consumed 1.378s CPU time.
app-steam@0dacf0eafc6749cdb9eda026c8e26576.service: Consumed 32.230s CPU time, 1.1G memory peak, 0B memory swap peak.
This plugin does not support raise()
Started app-org.kde.konsole@65aaf4a000af41709e4a28d23e33ae37.service - Konsole - Terminal.
mod.client-node: 0x55dc723578e0: unknown peer 0x55dc721a5480 fd:71
mod.client-node: 0x55dc720a7910: unknown peer 0x55dc7179d430 fd:92
mod.client-node: 0x55dc71850720: unknown peer 0x55dc7179d430 fd:71

```

## System
_Please complete the following information:_
 - Linux distribution Fedora 40
 - Burn-My-Windows version: 41
 - GNOME Shell version: KDE plasma 6.1

**Comment by chrostino** [comment]
no sorry I didn't, I'm not even on kde anymore

**Comment by ThierryBegin** [comment]
same issue for me too

**Comment by ThierryBegin** [comment]
> Did you ever fix this? Having the same problem KDE Plasma 6.5.1 on Wayland with Arch Linux

The comment from @TCMine is pretty much all that has been working so far, it's annoying but I've just ended up executing that command on a timer
